### PR TITLE
Refcard

### PR DESCRIPTION
**Pull request by aoighost**
Put the refcard in the book. Please verify everything is accurate/correct before merging.

### CODE REVIEW

**Comment by aoighost** [comment]
This pull request should fix #6 when done.

**Comment by crowell** [comment]
the refcard is not in `GITHUB FLAVORED MARKDOWN` please fix

**Comment by crowell** [comment]
Some of these things on the ref card are outdated. Searching for the aes keys for example.

**Comment by crowell** [comment]
By outdated I mean the command syntax has changed

**Comment by aoighost** [comment]
Alright, could you please list what is outdated and what needs to be changed and to what?

**Comment by crowell** [comment]
the search for aes keys should be `/Ca`
the search for xref to flags should be `axF`

not sure of the rest, but those were the few that jump out at me.

**Comment by Maijin** [comment]
Please merge guys you've got the access :)

**Comment by aoighost** [comment]
I'll update the refcard when I get back from Shmoo.

**Pull request merged**
